# Generated by Django 2.1.2 on 2018-10-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemyx', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
    ]
