# Generated by Django 2.1.1 on 2018-09-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_num', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Vendor'),
        ),
    ]
