# Generated by Django 2.1.1 on 2018-09-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='vendor_num',
            new_name='vendor',
        ),
    ]
