# Generated by Django 2.1.1 on 2018-09-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=500), null=True),
        ),
    ]
